name: "⛪ จองห้องประชุม - ตึก 2 Saint Benedict (ฝั่งอาคารเรียน)"
description: "เวลาทำการ 08:00 - 17:00 น. (จองได้ไม่เกิน 2 ชม./คน)"
title: "[Saint Benedict]: "
labels: ["รอตรวจสอบ⏳"]
body:
  - type: markdown
    attributes:
      value: |
        ### ระบบจองห้องประชุม ตึกที่ 2 Saint Benedict
        ⚠️ **เงื่อนไข:** เปิดทำการ 08:00 - 17:00 น. และจองใช้งานได้ **ไม่เกิน 2 ชั่วโมง ต่อคน / ต่อวัน** ครับ

  - type: dropdown
    id: room
    attributes:
      label: 🚪 เลือกห้องประชุมที่ต้องการใช้งาน
      options:
        - "Conference Room 1"
        - "Conference Room 2"
        - "mini theater room (เปิดใช้งานเร็วๆนี้)"
        - "multiple purpose room"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: 📆 วันที่ต้องการจอง
      placeholder: "ตัวอย่าง: 24 มิถุนายน 2026"
    validations:
      required: true

  - type: dropdown
    id: start_time
    attributes:
      label: ⏰ 1. เลือกเวลาที่ต้องการ "เริ่มต้น"
      options:
        - "08:00 น."
        - "08:30 น."
        - "09:00 น."
        - "09:30 น."
        - "10:00 น."
        - "10:30 น."
        - "11:00 น."
        - "11:30 น."
        - "12:00 น."
        - "12:30 น."
        - "13:00 น."
        - "13:30 น."
        - "14:00 น."
        - "14:30 น."
        - "15:00 น."
        - "15:30 น."
        - "16:00 น."
        - "16:30 น."
    validations:
      required: true

  - type: dropdown
    id: end_time
    attributes:
      label: ⏰ 2. เลือกเวลาที่ต้องการ "สิ้นสุด" (กรุณาเลือกให้ห่างจากเวลาเริ่มต้นไม่เกิน 2 ชั่วโมง)
      options:
        - "08:30 น."
        - "09:00 น."
        - "09:30 น."
        - "10:00 น."
        - "10:30 น."
        - "11:00 น."
        - "11:30 น."
        - "12:00 น."
        - "12:30 น."
        - "13:00 น."
        - "13:30 น."
        - "14:00 น."
        - "14:30 น."
        - "15:00 น."
        - "15:30 น."
        - "16:00 น."
        - "16:30 น."
        - "17:00 น."
    validations:
      required: true

  - type: input
    id: requester
    attributes:
      label: 👤 ชื่อผู้จอง / รหัสประจำตัว 
      placeholder: "ตัวอย่าง: นายโซล่าร์ 100xxx"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: 📝 วัตถุประสงค์การใช้งาน / รายชื่อผู้เข้าร่วม
      placeholder: "ระบุหัวข้อการประชุม หรือกิจกรรม..."
    validations:
      required: false
